blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & Discussions
    url: https://github.com/mstf66x/expo-firebase-starter/discussions
    about: Ask questions and share ideas here instead of opening an issue.
